//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type RiverClientQueue struct {
	RiverClientID    string `sql:"primary_key"`
	Name             string `sql:"primary_key"`
	CreatedAt        time.Time
	MaxWorkers       int64
	Metadata         string
	NumJobsCompleted int64
	NumJobsRunning   int64
	UpdatedAt        time.Time
}
