//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type UserMedicationScheduleLogStatus string

const (
	UserMedicationScheduleLogStatus_Upcoming UserMedicationScheduleLogStatus = "UPCOMING"
	UserMedicationScheduleLogStatus_Taken    UserMedicationScheduleLogStatus = "TAKEN"
	UserMedicationScheduleLogStatus_Missed   UserMedicationScheduleLogStatus = "MISSED"
)

var UserMedicationScheduleLogStatusAllValues = []UserMedicationScheduleLogStatus{
	UserMedicationScheduleLogStatus_Upcoming,
	UserMedicationScheduleLogStatus_Taken,
	UserMedicationScheduleLogStatus_Missed,
}

func (e *UserMedicationScheduleLogStatus) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "UPCOMING":
		*e = UserMedicationScheduleLogStatus_Upcoming
	case "TAKEN":
		*e = UserMedicationScheduleLogStatus_Taken
	case "MISSED":
		*e = UserMedicationScheduleLogStatus_Missed
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for UserMedicationScheduleLogStatus enum")
	}

	return nil
}

func (e UserMedicationScheduleLogStatus) String() string {
	return string(e)
}
