//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type UserMedicationMethodScheduleType string

const (
	UserMedicationMethodScheduleType_Days       UserMedicationMethodScheduleType = "DAYS"
	UserMedicationMethodScheduleType_Intervals  UserMedicationMethodScheduleType = "INTERVALS"
	UserMedicationMethodScheduleType_Periods    UserMedicationMethodScheduleType = "PERIODS"
	UserMedicationMethodScheduleType_WhenNeeded UserMedicationMethodScheduleType = "WHEN_NEEDED"
)

var UserMedicationMethodScheduleTypeAllValues = []UserMedicationMethodScheduleType{
	UserMedicationMethodScheduleType_Days,
	UserMedicationMethodScheduleType_Intervals,
	UserMedicationMethodScheduleType_Periods,
	UserMedicationMethodScheduleType_WhenNeeded,
}

func (e *UserMedicationMethodScheduleType) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "DAYS":
		*e = UserMedicationMethodScheduleType_Days
	case "INTERVALS":
		*e = UserMedicationMethodScheduleType_Intervals
	case "PERIODS":
		*e = UserMedicationMethodScheduleType_Periods
	case "WHEN_NEEDED":
		*e = UserMedicationMethodScheduleType_WhenNeeded
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for UserMedicationMethodScheduleType enum")
	}

	return nil
}

func (e UserMedicationMethodScheduleType) String() string {
	return string(e)
}
