//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type UserMedicationRecurringScheduleType string

const (
	UserMedicationRecurringScheduleType_Time       UserMedicationRecurringScheduleType = "TIME"
	UserMedicationRecurringScheduleType_Intervals  UserMedicationRecurringScheduleType = "INTERVALS"
	UserMedicationRecurringScheduleType_Periods    UserMedicationRecurringScheduleType = "PERIODS"
	UserMedicationRecurringScheduleType_WhenNeeded UserMedicationRecurringScheduleType = "WHEN_NEEDED"
)

var UserMedicationRecurringScheduleTypeAllValues = []UserMedicationRecurringScheduleType{
	UserMedicationRecurringScheduleType_Time,
	UserMedicationRecurringScheduleType_Intervals,
	UserMedicationRecurringScheduleType_Periods,
	UserMedicationRecurringScheduleType_WhenNeeded,
}

func (e *UserMedicationRecurringScheduleType) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "TIME":
		*e = UserMedicationRecurringScheduleType_Time
	case "INTERVALS":
		*e = UserMedicationRecurringScheduleType_Intervals
	case "PERIODS":
		*e = UserMedicationRecurringScheduleType_Periods
	case "WHEN_NEEDED":
		*e = UserMedicationRecurringScheduleType_WhenNeeded
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for UserMedicationRecurringScheduleType enum")
	}

	return nil
}

func (e UserMedicationRecurringScheduleType) String() string {
	return string(e)
}
