// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type AddMyMedicationInput struct {
	MedicationID    string    `json:"medicationId"`
	DosageStrength  string    `json:"dosageStrength"`
	ConsumptionTime time.Time `json:"consumptionTime"`
}

// Represents a medication.
type Medication struct {
	ID string `json:"id"`
	// The brand name of the medication. E.g. Tylenol.
	BrandName string `json:"brandName"`
	// The generic name of the medication. E.g. Acetaminophen.
	ActiveIngredient string `json:"activeIngredient"`
	// The forms of the medication. E.g. Capsule.
	DosageForms        []*string `json:"dosageForms"`
	StrengthsAvailable []string  `json:"strengthsAvailable,omitempty"`
}

type MedicationEdge struct {
	Cursor string      `json:"cursor"`
	Node   *Medication `json:"node"`
}

type MedicationsConnection struct {
	Edges    []*MedicationEdge `json:"edges"`
	PageInfo *PageInfo         `json:"pageInfo"`
}

type Mutation struct {
}

// Represents a medication that a user is taking.
type MyMedication struct {
	ID              string      `json:"id"`
	Medication      *Medication `json:"medication"`
	User            *User       `json:"user"`
	DosageStrength  string      `json:"dosageStrength"`
	ConsumptionTime time.Time   `json:"consumptionTime"`
}

type MyMedicationEdge struct {
	Cursor string        `json:"cursor"`
	Node   *MyMedication `json:"node"`
}

type MyMedicationsConnection struct {
	Edges    []*MyMedicationEdge `json:"edges"`
	PageInfo *PageInfo           `json:"pageInfo"`
}

type PageInfo struct {
	StartCursor string `json:"startCursor"`
	EndCursor   string `json:"endCursor"`
	HasNextPage *bool  `json:"hasNextPage,omitempty"`
}

type Query struct {
}

type User struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}
