//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Medications = newMedicationsTable("public", "medications", "")

type medicationsTable struct {
	postgres.Table

	// Columns
	ID                  postgres.ColumnString
	CreatedAt           postgres.ColumnTimestampz
	UpdatedAt           postgres.ColumnTimestampz
	DeletedAt           postgres.ColumnTimestampz
	Strength            postgres.ColumnString
	Name                postgres.ColumnString
	BrandName           postgres.ColumnString
	ActiveIngredient    postgres.ColumnString
	ActiveIngredientTsv postgres.ColumnString
	BrandNameTsv        postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type MedicationsTable struct {
	medicationsTable

	EXCLUDED medicationsTable
}

// AS creates new MedicationsTable with assigned alias
func (a MedicationsTable) AS(alias string) *MedicationsTable {
	return newMedicationsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new MedicationsTable with assigned schema name
func (a MedicationsTable) FromSchema(schemaName string) *MedicationsTable {
	return newMedicationsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new MedicationsTable with assigned table prefix
func (a MedicationsTable) WithPrefix(prefix string) *MedicationsTable {
	return newMedicationsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new MedicationsTable with assigned table suffix
func (a MedicationsTable) WithSuffix(suffix string) *MedicationsTable {
	return newMedicationsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newMedicationsTable(schemaName, tableName, alias string) *MedicationsTable {
	return &MedicationsTable{
		medicationsTable: newMedicationsTableImpl(schemaName, tableName, alias),
		EXCLUDED:         newMedicationsTableImpl("", "excluded", ""),
	}
}

func newMedicationsTableImpl(schemaName, tableName, alias string) medicationsTable {
	var (
		IDColumn                  = postgres.StringColumn("id")
		CreatedAtColumn           = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn           = postgres.TimestampzColumn("updated_at")
		DeletedAtColumn           = postgres.TimestampzColumn("deleted_at")
		StrengthColumn            = postgres.StringColumn("strength")
		NameColumn                = postgres.StringColumn("name")
		BrandNameColumn           = postgres.StringColumn("brand_name")
		ActiveIngredientColumn    = postgres.StringColumn("active_ingredient")
		ActiveIngredientTsvColumn = postgres.StringColumn("active_ingredient_tsv")
		BrandNameTsvColumn        = postgres.StringColumn("brand_name_tsv")
		allColumns                = postgres.ColumnList{IDColumn, CreatedAtColumn, UpdatedAtColumn, DeletedAtColumn, StrengthColumn, NameColumn, BrandNameColumn, ActiveIngredientColumn, ActiveIngredientTsvColumn, BrandNameTsvColumn}
		mutableColumns            = postgres.ColumnList{CreatedAtColumn, UpdatedAtColumn, DeletedAtColumn, StrengthColumn, NameColumn, BrandNameColumn, ActiveIngredientColumn}
	)

	return medicationsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                  IDColumn,
		CreatedAt:           CreatedAtColumn,
		UpdatedAt:           UpdatedAtColumn,
		DeletedAt:           DeletedAtColumn,
		Strength:            StrengthColumn,
		Name:                NameColumn,
		BrandName:           BrandNameColumn,
		ActiveIngredient:    ActiveIngredientColumn,
		ActiveIngredientTsv: ActiveIngredientTsvColumn,
		BrandNameTsv:        BrandNameTsvColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
