//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var NotificationDeliveries = newNotificationDeliveriesTable("public", "notification_deliveries", "")

type notificationDeliveriesTable struct {
	postgres.Table

	// Columns
	UserMedicationScheduleID postgres.ColumnString
	NotificationDate         postgres.ColumnTimestampz
	Status                   postgres.ColumnString
	CreatedAt                postgres.ColumnTimestampz
	UpdatedAt                postgres.ColumnTimestampz
	DeletedAt                postgres.ColumnTimestampz
	ID                       postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type NotificationDeliveriesTable struct {
	notificationDeliveriesTable

	EXCLUDED notificationDeliveriesTable
}

// AS creates new NotificationDeliveriesTable with assigned alias
func (a NotificationDeliveriesTable) AS(alias string) *NotificationDeliveriesTable {
	return newNotificationDeliveriesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new NotificationDeliveriesTable with assigned schema name
func (a NotificationDeliveriesTable) FromSchema(schemaName string) *NotificationDeliveriesTable {
	return newNotificationDeliveriesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new NotificationDeliveriesTable with assigned table prefix
func (a NotificationDeliveriesTable) WithPrefix(prefix string) *NotificationDeliveriesTable {
	return newNotificationDeliveriesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new NotificationDeliveriesTable with assigned table suffix
func (a NotificationDeliveriesTable) WithSuffix(suffix string) *NotificationDeliveriesTable {
	return newNotificationDeliveriesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newNotificationDeliveriesTable(schemaName, tableName, alias string) *NotificationDeliveriesTable {
	return &NotificationDeliveriesTable{
		notificationDeliveriesTable: newNotificationDeliveriesTableImpl(schemaName, tableName, alias),
		EXCLUDED:                    newNotificationDeliveriesTableImpl("", "excluded", ""),
	}
}

func newNotificationDeliveriesTableImpl(schemaName, tableName, alias string) notificationDeliveriesTable {
	var (
		UserMedicationScheduleIDColumn = postgres.StringColumn("user_medication_schedule_id")
		NotificationDateColumn         = postgres.TimestampzColumn("notification_date")
		StatusColumn                   = postgres.StringColumn("status")
		CreatedAtColumn                = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn                = postgres.TimestampzColumn("updated_at")
		DeletedAtColumn                = postgres.TimestampzColumn("deleted_at")
		IDColumn                       = postgres.StringColumn("id")
		allColumns                     = postgres.ColumnList{UserMedicationScheduleIDColumn, NotificationDateColumn, StatusColumn, CreatedAtColumn, UpdatedAtColumn, DeletedAtColumn, IDColumn}
		mutableColumns                 = postgres.ColumnList{UserMedicationScheduleIDColumn, NotificationDateColumn, StatusColumn, CreatedAtColumn, UpdatedAtColumn, DeletedAtColumn, IDColumn}
	)

	return notificationDeliveriesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		UserMedicationScheduleID: UserMedicationScheduleIDColumn,
		NotificationDate:         NotificationDateColumn,
		Status:                   StatusColumn,
		CreatedAt:                CreatedAtColumn,
		UpdatedAt:                UpdatedAtColumn,
		DeletedAt:                DeletedAtColumn,
		ID:                       IDColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
