//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var RiverClientQueue = newRiverClientQueueTable("public", "river_client_queue", "")

type riverClientQueueTable struct {
	postgres.Table

	// Columns
	RiverClientID    postgres.ColumnString
	Name             postgres.ColumnString
	CreatedAt        postgres.ColumnTimestampz
	MaxWorkers       postgres.ColumnInteger
	Metadata         postgres.ColumnString
	NumJobsCompleted postgres.ColumnInteger
	NumJobsRunning   postgres.ColumnInteger
	UpdatedAt        postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type RiverClientQueueTable struct {
	riverClientQueueTable

	EXCLUDED riverClientQueueTable
}

// AS creates new RiverClientQueueTable with assigned alias
func (a RiverClientQueueTable) AS(alias string) *RiverClientQueueTable {
	return newRiverClientQueueTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new RiverClientQueueTable with assigned schema name
func (a RiverClientQueueTable) FromSchema(schemaName string) *RiverClientQueueTable {
	return newRiverClientQueueTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new RiverClientQueueTable with assigned table prefix
func (a RiverClientQueueTable) WithPrefix(prefix string) *RiverClientQueueTable {
	return newRiverClientQueueTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new RiverClientQueueTable with assigned table suffix
func (a RiverClientQueueTable) WithSuffix(suffix string) *RiverClientQueueTable {
	return newRiverClientQueueTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newRiverClientQueueTable(schemaName, tableName, alias string) *RiverClientQueueTable {
	return &RiverClientQueueTable{
		riverClientQueueTable: newRiverClientQueueTableImpl(schemaName, tableName, alias),
		EXCLUDED:              newRiverClientQueueTableImpl("", "excluded", ""),
	}
}

func newRiverClientQueueTableImpl(schemaName, tableName, alias string) riverClientQueueTable {
	var (
		RiverClientIDColumn    = postgres.StringColumn("river_client_id")
		NameColumn             = postgres.StringColumn("name")
		CreatedAtColumn        = postgres.TimestampzColumn("created_at")
		MaxWorkersColumn       = postgres.IntegerColumn("max_workers")
		MetadataColumn         = postgres.StringColumn("metadata")
		NumJobsCompletedColumn = postgres.IntegerColumn("num_jobs_completed")
		NumJobsRunningColumn   = postgres.IntegerColumn("num_jobs_running")
		UpdatedAtColumn        = postgres.TimestampzColumn("updated_at")
		allColumns             = postgres.ColumnList{RiverClientIDColumn, NameColumn, CreatedAtColumn, MaxWorkersColumn, MetadataColumn, NumJobsCompletedColumn, NumJobsRunningColumn, UpdatedAtColumn}
		mutableColumns         = postgres.ColumnList{CreatedAtColumn, MaxWorkersColumn, MetadataColumn, NumJobsCompletedColumn, NumJobsRunningColumn, UpdatedAtColumn}
	)

	return riverClientQueueTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		RiverClientID:    RiverClientIDColumn,
		Name:             NameColumn,
		CreatedAt:        CreatedAtColumn,
		MaxWorkers:       MaxWorkersColumn,
		Metadata:         MetadataColumn,
		NumJobsCompleted: NumJobsCompletedColumn,
		NumJobsRunning:   NumJobsRunningColumn,
		UpdatedAt:        UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
