//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var RiverMigration = newRiverMigrationTable("public", "river_migration", "")

type riverMigrationTable struct {
	postgres.Table

	// Columns
	Line      postgres.ColumnString
	Version   postgres.ColumnInteger
	CreatedAt postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type RiverMigrationTable struct {
	riverMigrationTable

	EXCLUDED riverMigrationTable
}

// AS creates new RiverMigrationTable with assigned alias
func (a RiverMigrationTable) AS(alias string) *RiverMigrationTable {
	return newRiverMigrationTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new RiverMigrationTable with assigned schema name
func (a RiverMigrationTable) FromSchema(schemaName string) *RiverMigrationTable {
	return newRiverMigrationTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new RiverMigrationTable with assigned table prefix
func (a RiverMigrationTable) WithPrefix(prefix string) *RiverMigrationTable {
	return newRiverMigrationTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new RiverMigrationTable with assigned table suffix
func (a RiverMigrationTable) WithSuffix(suffix string) *RiverMigrationTable {
	return newRiverMigrationTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newRiverMigrationTable(schemaName, tableName, alias string) *RiverMigrationTable {
	return &RiverMigrationTable{
		riverMigrationTable: newRiverMigrationTableImpl(schemaName, tableName, alias),
		EXCLUDED:            newRiverMigrationTableImpl("", "excluded", ""),
	}
}

func newRiverMigrationTableImpl(schemaName, tableName, alias string) riverMigrationTable {
	var (
		LineColumn      = postgres.StringColumn("line")
		VersionColumn   = postgres.IntegerColumn("version")
		CreatedAtColumn = postgres.TimestampzColumn("created_at")
		allColumns      = postgres.ColumnList{LineColumn, VersionColumn, CreatedAtColumn}
		mutableColumns  = postgres.ColumnList{CreatedAtColumn}
	)

	return riverMigrationTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		Line:      LineColumn,
		Version:   VersionColumn,
		CreatedAt: CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
