//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var RiverQueue = newRiverQueueTable("public", "river_queue", "")

type riverQueueTable struct {
	postgres.Table

	// Columns
	Name      postgres.ColumnString
	CreatedAt postgres.ColumnTimestampz
	Metadata  postgres.ColumnString
	PausedAt  postgres.ColumnTimestampz
	UpdatedAt postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type RiverQueueTable struct {
	riverQueueTable

	EXCLUDED riverQueueTable
}

// AS creates new RiverQueueTable with assigned alias
func (a RiverQueueTable) AS(alias string) *RiverQueueTable {
	return newRiverQueueTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new RiverQueueTable with assigned schema name
func (a RiverQueueTable) FromSchema(schemaName string) *RiverQueueTable {
	return newRiverQueueTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new RiverQueueTable with assigned table prefix
func (a RiverQueueTable) WithPrefix(prefix string) *RiverQueueTable {
	return newRiverQueueTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new RiverQueueTable with assigned table suffix
func (a RiverQueueTable) WithSuffix(suffix string) *RiverQueueTable {
	return newRiverQueueTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newRiverQueueTable(schemaName, tableName, alias string) *RiverQueueTable {
	return &RiverQueueTable{
		riverQueueTable: newRiverQueueTableImpl(schemaName, tableName, alias),
		EXCLUDED:        newRiverQueueTableImpl("", "excluded", ""),
	}
}

func newRiverQueueTableImpl(schemaName, tableName, alias string) riverQueueTable {
	var (
		NameColumn      = postgres.StringColumn("name")
		CreatedAtColumn = postgres.TimestampzColumn("created_at")
		MetadataColumn  = postgres.StringColumn("metadata")
		PausedAtColumn  = postgres.TimestampzColumn("paused_at")
		UpdatedAtColumn = postgres.TimestampzColumn("updated_at")
		allColumns      = postgres.ColumnList{NameColumn, CreatedAtColumn, MetadataColumn, PausedAtColumn, UpdatedAtColumn}
		mutableColumns  = postgres.ColumnList{CreatedAtColumn, MetadataColumn, PausedAtColumn, UpdatedAtColumn}
	)

	return riverQueueTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		Name:      NameColumn,
		CreatedAt: CreatedAtColumn,
		Metadata:  MetadataColumn,
		PausedAt:  PausedAtColumn,
		UpdatedAt: UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
