//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var UserFcmTokens = newUserFcmTokensTable("public", "user_fcm_tokens", "")

type userFcmTokensTable struct {
	postgres.Table

	// Columns
	ID        postgres.ColumnString
	CreatedAt postgres.ColumnTimestampz
	UpdatedAt postgres.ColumnTimestampz
	DeletedAt postgres.ColumnTimestampz
	Token     postgres.ColumnString
	UserID    postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type UserFcmTokensTable struct {
	userFcmTokensTable

	EXCLUDED userFcmTokensTable
}

// AS creates new UserFcmTokensTable with assigned alias
func (a UserFcmTokensTable) AS(alias string) *UserFcmTokensTable {
	return newUserFcmTokensTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new UserFcmTokensTable with assigned schema name
func (a UserFcmTokensTable) FromSchema(schemaName string) *UserFcmTokensTable {
	return newUserFcmTokensTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new UserFcmTokensTable with assigned table prefix
func (a UserFcmTokensTable) WithPrefix(prefix string) *UserFcmTokensTable {
	return newUserFcmTokensTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new UserFcmTokensTable with assigned table suffix
func (a UserFcmTokensTable) WithSuffix(suffix string) *UserFcmTokensTable {
	return newUserFcmTokensTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newUserFcmTokensTable(schemaName, tableName, alias string) *UserFcmTokensTable {
	return &UserFcmTokensTable{
		userFcmTokensTable: newUserFcmTokensTableImpl(schemaName, tableName, alias),
		EXCLUDED:           newUserFcmTokensTableImpl("", "excluded", ""),
	}
}

func newUserFcmTokensTableImpl(schemaName, tableName, alias string) userFcmTokensTable {
	var (
		IDColumn        = postgres.StringColumn("id")
		CreatedAtColumn = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn = postgres.TimestampzColumn("updated_at")
		DeletedAtColumn = postgres.TimestampzColumn("deleted_at")
		TokenColumn     = postgres.StringColumn("token")
		UserIDColumn    = postgres.StringColumn("user_id")
		allColumns      = postgres.ColumnList{IDColumn, CreatedAtColumn, UpdatedAtColumn, DeletedAtColumn, TokenColumn, UserIDColumn}
		mutableColumns  = postgres.ColumnList{CreatedAtColumn, UpdatedAtColumn, DeletedAtColumn, TokenColumn, UserIDColumn}
	)

	return userFcmTokensTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		CreatedAt: CreatedAtColumn,
		UpdatedAt: UpdatedAtColumn,
		DeletedAt: DeletedAtColumn,
		Token:     TokenColumn,
		UserID:    UserIDColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
