//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var UserMedications = newUserMedicationsTable("public", "user_medications", "")

type userMedicationsTable struct {
	postgres.Table

	// Columns
	ID               postgres.ColumnString
	CreatedAt        postgres.ColumnTimestampz
	UpdatedAt        postgres.ColumnTimestampz
	DeletedAt        postgres.ColumnTimestampz
	UserID           postgres.ColumnString
	MedicationID     postgres.ColumnString
	Strength         postgres.ColumnString
	ReminderDateTime postgres.ColumnTimestampz
	Name             postgres.ColumnString
	TagLinked        postgres.ColumnBool

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type UserMedicationsTable struct {
	userMedicationsTable

	EXCLUDED userMedicationsTable
}

// AS creates new UserMedicationsTable with assigned alias
func (a UserMedicationsTable) AS(alias string) *UserMedicationsTable {
	return newUserMedicationsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new UserMedicationsTable with assigned schema name
func (a UserMedicationsTable) FromSchema(schemaName string) *UserMedicationsTable {
	return newUserMedicationsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new UserMedicationsTable with assigned table prefix
func (a UserMedicationsTable) WithPrefix(prefix string) *UserMedicationsTable {
	return newUserMedicationsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new UserMedicationsTable with assigned table suffix
func (a UserMedicationsTable) WithSuffix(suffix string) *UserMedicationsTable {
	return newUserMedicationsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newUserMedicationsTable(schemaName, tableName, alias string) *UserMedicationsTable {
	return &UserMedicationsTable{
		userMedicationsTable: newUserMedicationsTableImpl(schemaName, tableName, alias),
		EXCLUDED:             newUserMedicationsTableImpl("", "excluded", ""),
	}
}

func newUserMedicationsTableImpl(schemaName, tableName, alias string) userMedicationsTable {
	var (
		IDColumn               = postgres.StringColumn("id")
		CreatedAtColumn        = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn        = postgres.TimestampzColumn("updated_at")
		DeletedAtColumn        = postgres.TimestampzColumn("deleted_at")
		UserIDColumn           = postgres.StringColumn("user_id")
		MedicationIDColumn     = postgres.StringColumn("medication_id")
		StrengthColumn         = postgres.StringColumn("strength")
		ReminderDateTimeColumn = postgres.TimestampzColumn("reminder_date_time")
		NameColumn             = postgres.StringColumn("name")
		TagLinkedColumn        = postgres.BoolColumn("tag_linked")
		allColumns             = postgres.ColumnList{IDColumn, CreatedAtColumn, UpdatedAtColumn, DeletedAtColumn, UserIDColumn, MedicationIDColumn, StrengthColumn, ReminderDateTimeColumn, NameColumn, TagLinkedColumn}
		mutableColumns         = postgres.ColumnList{CreatedAtColumn, UpdatedAtColumn, DeletedAtColumn, UserIDColumn, MedicationIDColumn, StrengthColumn, ReminderDateTimeColumn, NameColumn, TagLinkedColumn}
	)

	return userMedicationsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:               IDColumn,
		CreatedAt:        CreatedAtColumn,
		UpdatedAt:        UpdatedAtColumn,
		DeletedAt:        DeletedAtColumn,
		UserID:           UserIDColumn,
		MedicationID:     MedicationIDColumn,
		Strength:         StrengthColumn,
		ReminderDateTime: ReminderDateTimeColumn,
		Name:             NameColumn,
		TagLinked:        TagLinkedColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
