//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var UserMedicationConsumptions = newUserMedicationConsumptionsTable("public", "user_medication_consumptions", "")

type userMedicationConsumptionsTable struct {
	postgres.Table

	// Columns
	ID               postgres.ColumnString
	CreatedAt        postgres.ColumnTimestampz
	UpdatedAt        postgres.ColumnTimestampz
	DeletedAt        postgres.ColumnTimestampz
	DueDate          postgres.ColumnTimestampz
	Status           postgres.ColumnString
	UserMedicationID postgres.ColumnString
	DoseDate         postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type UserMedicationConsumptionsTable struct {
	userMedicationConsumptionsTable

	EXCLUDED userMedicationConsumptionsTable
}

// AS creates new UserMedicationConsumptionsTable with assigned alias
func (a UserMedicationConsumptionsTable) AS(alias string) *UserMedicationConsumptionsTable {
	return newUserMedicationConsumptionsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new UserMedicationConsumptionsTable with assigned schema name
func (a UserMedicationConsumptionsTable) FromSchema(schemaName string) *UserMedicationConsumptionsTable {
	return newUserMedicationConsumptionsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new UserMedicationConsumptionsTable with assigned table prefix
func (a UserMedicationConsumptionsTable) WithPrefix(prefix string) *UserMedicationConsumptionsTable {
	return newUserMedicationConsumptionsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new UserMedicationConsumptionsTable with assigned table suffix
func (a UserMedicationConsumptionsTable) WithSuffix(suffix string) *UserMedicationConsumptionsTable {
	return newUserMedicationConsumptionsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newUserMedicationConsumptionsTable(schemaName, tableName, alias string) *UserMedicationConsumptionsTable {
	return &UserMedicationConsumptionsTable{
		userMedicationConsumptionsTable: newUserMedicationConsumptionsTableImpl(schemaName, tableName, alias),
		EXCLUDED:                        newUserMedicationConsumptionsTableImpl("", "excluded", ""),
	}
}

func newUserMedicationConsumptionsTableImpl(schemaName, tableName, alias string) userMedicationConsumptionsTable {
	var (
		IDColumn               = postgres.StringColumn("id")
		CreatedAtColumn        = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn        = postgres.TimestampzColumn("updated_at")
		DeletedAtColumn        = postgres.TimestampzColumn("deleted_at")
		DueDateColumn          = postgres.TimestampzColumn("due_date")
		StatusColumn           = postgres.StringColumn("status")
		UserMedicationIDColumn = postgres.StringColumn("user_medication_id")
		DoseDateColumn         = postgres.TimestampzColumn("dose_date")
		allColumns             = postgres.ColumnList{IDColumn, CreatedAtColumn, UpdatedAtColumn, DeletedAtColumn, DueDateColumn, StatusColumn, UserMedicationIDColumn, DoseDateColumn}
		mutableColumns         = postgres.ColumnList{CreatedAtColumn, UpdatedAtColumn, DeletedAtColumn, DueDateColumn, StatusColumn, UserMedicationIDColumn, DoseDateColumn}
	)

	return userMedicationConsumptionsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:               IDColumn,
		CreatedAt:        CreatedAtColumn,
		UpdatedAt:        UpdatedAtColumn,
		DeletedAt:        DeletedAtColumn,
		DueDate:          DueDateColumn,
		Status:           StatusColumn,
		UserMedicationID: UserMedicationIDColumn,
		DoseDate:         DoseDateColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
