// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                      = new(Query)
	Medication             *medication
	User                   *user
	UserFCMToken           *userFCMToken
	UserMedication         *userMedication
	UserMedicationSchedule *userMedicationSchedule
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Medication = &Q.Medication
	User = &Q.User
	UserFCMToken = &Q.UserFCMToken
	UserMedication = &Q.UserMedication
	UserMedicationSchedule = &Q.UserMedicationSchedule
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                     db,
		Medication:             newMedication(db, opts...),
		User:                   newUser(db, opts...),
		UserFCMToken:           newUserFCMToken(db, opts...),
		UserMedication:         newUserMedication(db, opts...),
		UserMedicationSchedule: newUserMedicationSchedule(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Medication             medication
	User                   user
	UserFCMToken           userFCMToken
	UserMedication         userMedication
	UserMedicationSchedule userMedicationSchedule
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                     db,
		Medication:             q.Medication.clone(db),
		User:                   q.User.clone(db),
		UserFCMToken:           q.UserFCMToken.clone(db),
		UserMedication:         q.UserMedication.clone(db),
		UserMedicationSchedule: q.UserMedicationSchedule.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                     db,
		Medication:             q.Medication.replaceDB(db),
		User:                   q.User.replaceDB(db),
		UserFCMToken:           q.UserFCMToken.replaceDB(db),
		UserMedication:         q.UserMedication.replaceDB(db),
		UserMedicationSchedule: q.UserMedicationSchedule.replaceDB(db),
	}
}

type queryCtx struct {
	Medication             IMedicationDo
	User                   IUserDo
	UserFCMToken           IUserFCMTokenDo
	UserMedication         IUserMedicationDo
	UserMedicationSchedule IUserMedicationScheduleDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Medication:             q.Medication.WithContext(ctx),
		User:                   q.User.WithContext(ctx),
		UserFCMToken:           q.UserFCMToken.WithContext(ctx),
		UserMedication:         q.UserMedication.WithContext(ctx),
		UserMedicationSchedule: q.UserMedicationSchedule.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
