// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/joshnissenbaum/scriptag-platform/shared/models"
)

func newMedication(db *gorm.DB, opts ...gen.DOOption) medication {
	_medication := medication{}

	_medication.medicationDo.UseDB(db, opts...)
	_medication.medicationDo.UseModel(&models.Medication{})

	tableName := _medication.medicationDo.TableName()
	_medication.ALL = field.NewAsterisk(tableName)
	_medication.ID = field.NewString(tableName, "id")
	_medication.CreatedAt = field.NewTime(tableName, "created_at")
	_medication.UpdatedAt = field.NewTime(tableName, "updated_at")
	_medication.DeletedAt = field.NewField(tableName, "deleted_at")
	_medication.BrandName = field.NewString(tableName, "brand_name")
	_medication.ActiveIngredient = field.NewString(tableName, "active_ingredient")
	_medication.Strength = field.NewString(tableName, "strength")

	_medication.fillFieldMap()

	return _medication
}

type medication struct {
	medicationDo

	ALL              field.Asterisk
	ID               field.String
	CreatedAt        field.Time
	UpdatedAt        field.Time
	DeletedAt        field.Field
	BrandName        field.String
	ActiveIngredient field.String
	Strength         field.String

	fieldMap map[string]field.Expr
}

func (m medication) Table(newTableName string) *medication {
	m.medicationDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m medication) As(alias string) *medication {
	m.medicationDo.DO = *(m.medicationDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *medication) updateTableName(table string) *medication {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewString(table, "id")
	m.CreatedAt = field.NewTime(table, "created_at")
	m.UpdatedAt = field.NewTime(table, "updated_at")
	m.DeletedAt = field.NewField(table, "deleted_at")
	m.BrandName = field.NewString(table, "brand_name")
	m.ActiveIngredient = field.NewString(table, "active_ingredient")
	m.Strength = field.NewString(table, "strength")

	m.fillFieldMap()

	return m
}

func (m *medication) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *medication) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 7)
	m.fieldMap["id"] = m.ID
	m.fieldMap["created_at"] = m.CreatedAt
	m.fieldMap["updated_at"] = m.UpdatedAt
	m.fieldMap["deleted_at"] = m.DeletedAt
	m.fieldMap["brand_name"] = m.BrandName
	m.fieldMap["active_ingredient"] = m.ActiveIngredient
	m.fieldMap["strength"] = m.Strength
}

func (m medication) clone(db *gorm.DB) medication {
	m.medicationDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m medication) replaceDB(db *gorm.DB) medication {
	m.medicationDo.ReplaceDB(db)
	return m
}

type medicationDo struct{ gen.DO }

type IMedicationDo interface {
	gen.SubQuery
	Debug() IMedicationDo
	WithContext(ctx context.Context) IMedicationDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMedicationDo
	WriteDB() IMedicationDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMedicationDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMedicationDo
	Not(conds ...gen.Condition) IMedicationDo
	Or(conds ...gen.Condition) IMedicationDo
	Select(conds ...field.Expr) IMedicationDo
	Where(conds ...gen.Condition) IMedicationDo
	Order(conds ...field.Expr) IMedicationDo
	Distinct(cols ...field.Expr) IMedicationDo
	Omit(cols ...field.Expr) IMedicationDo
	Join(table schema.Tabler, on ...field.Expr) IMedicationDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IMedicationDo
	RightJoin(table schema.Tabler, on ...field.Expr) IMedicationDo
	Group(cols ...field.Expr) IMedicationDo
	Having(conds ...gen.Condition) IMedicationDo
	Limit(limit int) IMedicationDo
	Offset(offset int) IMedicationDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMedicationDo
	Unscoped() IMedicationDo
	Create(values ...*models.Medication) error
	CreateInBatches(values []*models.Medication, batchSize int) error
	Save(values ...*models.Medication) error
	First() (*models.Medication, error)
	Take() (*models.Medication, error)
	Last() (*models.Medication, error)
	Find() ([]*models.Medication, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Medication, err error)
	FindInBatches(result *[]*models.Medication, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.Medication) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMedicationDo
	Assign(attrs ...field.AssignExpr) IMedicationDo
	Joins(fields ...field.RelationField) IMedicationDo
	Preload(fields ...field.RelationField) IMedicationDo
	FirstOrInit() (*models.Medication, error)
	FirstOrCreate() (*models.Medication, error)
	FindByPage(offset int, limit int) (result []*models.Medication, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMedicationDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m medicationDo) Debug() IMedicationDo {
	return m.withDO(m.DO.Debug())
}

func (m medicationDo) WithContext(ctx context.Context) IMedicationDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m medicationDo) ReadDB() IMedicationDo {
	return m.Clauses(dbresolver.Read)
}

func (m medicationDo) WriteDB() IMedicationDo {
	return m.Clauses(dbresolver.Write)
}

func (m medicationDo) Session(config *gorm.Session) IMedicationDo {
	return m.withDO(m.DO.Session(config))
}

func (m medicationDo) Clauses(conds ...clause.Expression) IMedicationDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m medicationDo) Returning(value interface{}, columns ...string) IMedicationDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m medicationDo) Not(conds ...gen.Condition) IMedicationDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m medicationDo) Or(conds ...gen.Condition) IMedicationDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m medicationDo) Select(conds ...field.Expr) IMedicationDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m medicationDo) Where(conds ...gen.Condition) IMedicationDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m medicationDo) Order(conds ...field.Expr) IMedicationDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m medicationDo) Distinct(cols ...field.Expr) IMedicationDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m medicationDo) Omit(cols ...field.Expr) IMedicationDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m medicationDo) Join(table schema.Tabler, on ...field.Expr) IMedicationDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m medicationDo) LeftJoin(table schema.Tabler, on ...field.Expr) IMedicationDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m medicationDo) RightJoin(table schema.Tabler, on ...field.Expr) IMedicationDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m medicationDo) Group(cols ...field.Expr) IMedicationDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m medicationDo) Having(conds ...gen.Condition) IMedicationDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m medicationDo) Limit(limit int) IMedicationDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m medicationDo) Offset(offset int) IMedicationDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m medicationDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IMedicationDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m medicationDo) Unscoped() IMedicationDo {
	return m.withDO(m.DO.Unscoped())
}

func (m medicationDo) Create(values ...*models.Medication) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m medicationDo) CreateInBatches(values []*models.Medication, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m medicationDo) Save(values ...*models.Medication) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m medicationDo) First() (*models.Medication, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.Medication), nil
	}
}

func (m medicationDo) Take() (*models.Medication, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.Medication), nil
	}
}

func (m medicationDo) Last() (*models.Medication, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.Medication), nil
	}
}

func (m medicationDo) Find() ([]*models.Medication, error) {
	result, err := m.DO.Find()
	return result.([]*models.Medication), err
}

func (m medicationDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Medication, err error) {
	buf := make([]*models.Medication, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m medicationDo) FindInBatches(result *[]*models.Medication, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m medicationDo) Attrs(attrs ...field.AssignExpr) IMedicationDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m medicationDo) Assign(attrs ...field.AssignExpr) IMedicationDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m medicationDo) Joins(fields ...field.RelationField) IMedicationDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m medicationDo) Preload(fields ...field.RelationField) IMedicationDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m medicationDo) FirstOrInit() (*models.Medication, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.Medication), nil
	}
}

func (m medicationDo) FirstOrCreate() (*models.Medication, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.Medication), nil
	}
}

func (m medicationDo) FindByPage(offset int, limit int) (result []*models.Medication, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m medicationDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m medicationDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m medicationDo) Delete(models ...*models.Medication) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *medicationDo) withDO(do gen.Dao) *medicationDo {
	m.DO = *do.(*gen.DO)
	return m
}
