// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/joshnissenbaum/scriptag-platform/shared/models"
)

func newUserMedicationSchedule(db *gorm.DB, opts ...gen.DOOption) userMedicationSchedule {
	_userMedicationSchedule := userMedicationSchedule{}

	_userMedicationSchedule.userMedicationScheduleDo.UseDB(db, opts...)
	_userMedicationSchedule.userMedicationScheduleDo.UseModel(&models.UserMedicationSchedule{})

	tableName := _userMedicationSchedule.userMedicationScheduleDo.TableName()
	_userMedicationSchedule.ALL = field.NewAsterisk(tableName)
	_userMedicationSchedule.ID = field.NewString(tableName, "id")
	_userMedicationSchedule.CreatedAt = field.NewTime(tableName, "created_at")
	_userMedicationSchedule.UpdatedAt = field.NewTime(tableName, "updated_at")
	_userMedicationSchedule.DeletedAt = field.NewField(tableName, "deleted_at")
	_userMedicationSchedule.UserMedicationID = field.NewString(tableName, "user_medication_id")
	_userMedicationSchedule.MethodType = field.NewString(tableName, "method_type")
	_userMedicationSchedule.RecurringType = field.NewString(tableName, "recurring_type")
	_userMedicationSchedule.DaysOfWeek = field.NewField(tableName, "days_of_week")
	_userMedicationSchedule.TimeSlots = field.NewField(tableName, "time_slots")
	_userMedicationSchedule.StartDate = field.NewTime(tableName, "start_date")
	_userMedicationSchedule.EndDate = field.NewTime(tableName, "end_date")
	_userMedicationSchedule.DaysInterval = field.NewUint(tableName, "days_interval")
	_userMedicationSchedule.HoursInterval = field.NewUint(tableName, "hours_interval")
	_userMedicationSchedule.UseForDays = field.NewUint(tableName, "use_for_days")
	_userMedicationSchedule.PauseForDays = field.NewUint(tableName, "pause_for_days")
	_userMedicationSchedule.UseForHours = field.NewUint(tableName, "use_for_hours")
	_userMedicationSchedule.PauseForHours = field.NewUint(tableName, "pause_for_hours")
	_userMedicationSchedule.RefillsAmount = field.NewUint(tableName, "refills_amount")
	_userMedicationSchedule.DosesAmount = field.NewUint(tableName, "doses_amount")
	_userMedicationSchedule.UserMedication = userMedicationScheduleBelongsToUserMedication{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("UserMedication", "models.UserMedication"),
		User: struct {
			field.RelationField
			FCMTokens struct {
				field.RelationField
				User struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("UserMedication.User", "models.User"),
			FCMTokens: struct {
				field.RelationField
				User struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("UserMedication.User.FCMTokens", "models.UserFCMToken"),
				User: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("UserMedication.User.FCMTokens.User", "models.User"),
				},
			},
		},
		Medication: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("UserMedication.Medication", "models.Medication"),
		},
		Schedule: struct {
			field.RelationField
			UserMedication struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("UserMedication.Schedule", "models.UserMedicationSchedule"),
			UserMedication: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("UserMedication.Schedule.UserMedication", "models.UserMedication"),
			},
		},
	}

	_userMedicationSchedule.fillFieldMap()

	return _userMedicationSchedule
}

type userMedicationSchedule struct {
	userMedicationScheduleDo

	ALL              field.Asterisk
	ID               field.String
	CreatedAt        field.Time
	UpdatedAt        field.Time
	DeletedAt        field.Field
	UserMedicationID field.String
	MethodType       field.String
	RecurringType    field.String
	DaysOfWeek       field.Field
	TimeSlots        field.Field
	StartDate        field.Time
	EndDate          field.Time
	DaysInterval     field.Uint
	HoursInterval    field.Uint
	UseForDays       field.Uint
	PauseForDays     field.Uint
	UseForHours      field.Uint
	PauseForHours    field.Uint
	RefillsAmount    field.Uint
	DosesAmount      field.Uint
	UserMedication   userMedicationScheduleBelongsToUserMedication

	fieldMap map[string]field.Expr
}

func (u userMedicationSchedule) Table(newTableName string) *userMedicationSchedule {
	u.userMedicationScheduleDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u userMedicationSchedule) As(alias string) *userMedicationSchedule {
	u.userMedicationScheduleDo.DO = *(u.userMedicationScheduleDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *userMedicationSchedule) updateTableName(table string) *userMedicationSchedule {
	u.ALL = field.NewAsterisk(table)
	u.ID = field.NewString(table, "id")
	u.CreatedAt = field.NewTime(table, "created_at")
	u.UpdatedAt = field.NewTime(table, "updated_at")
	u.DeletedAt = field.NewField(table, "deleted_at")
	u.UserMedicationID = field.NewString(table, "user_medication_id")
	u.MethodType = field.NewString(table, "method_type")
	u.RecurringType = field.NewString(table, "recurring_type")
	u.DaysOfWeek = field.NewField(table, "days_of_week")
	u.TimeSlots = field.NewField(table, "time_slots")
	u.StartDate = field.NewTime(table, "start_date")
	u.EndDate = field.NewTime(table, "end_date")
	u.DaysInterval = field.NewUint(table, "days_interval")
	u.HoursInterval = field.NewUint(table, "hours_interval")
	u.UseForDays = field.NewUint(table, "use_for_days")
	u.PauseForDays = field.NewUint(table, "pause_for_days")
	u.UseForHours = field.NewUint(table, "use_for_hours")
	u.PauseForHours = field.NewUint(table, "pause_for_hours")
	u.RefillsAmount = field.NewUint(table, "refills_amount")
	u.DosesAmount = field.NewUint(table, "doses_amount")

	u.fillFieldMap()

	return u
}

func (u *userMedicationSchedule) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *userMedicationSchedule) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 20)
	u.fieldMap["id"] = u.ID
	u.fieldMap["created_at"] = u.CreatedAt
	u.fieldMap["updated_at"] = u.UpdatedAt
	u.fieldMap["deleted_at"] = u.DeletedAt
	u.fieldMap["user_medication_id"] = u.UserMedicationID
	u.fieldMap["method_type"] = u.MethodType
	u.fieldMap["recurring_type"] = u.RecurringType
	u.fieldMap["days_of_week"] = u.DaysOfWeek
	u.fieldMap["time_slots"] = u.TimeSlots
	u.fieldMap["start_date"] = u.StartDate
	u.fieldMap["end_date"] = u.EndDate
	u.fieldMap["days_interval"] = u.DaysInterval
	u.fieldMap["hours_interval"] = u.HoursInterval
	u.fieldMap["use_for_days"] = u.UseForDays
	u.fieldMap["pause_for_days"] = u.PauseForDays
	u.fieldMap["use_for_hours"] = u.UseForHours
	u.fieldMap["pause_for_hours"] = u.PauseForHours
	u.fieldMap["refills_amount"] = u.RefillsAmount
	u.fieldMap["doses_amount"] = u.DosesAmount

}

func (u userMedicationSchedule) clone(db *gorm.DB) userMedicationSchedule {
	u.userMedicationScheduleDo.ReplaceConnPool(db.Statement.ConnPool)
	return u
}

func (u userMedicationSchedule) replaceDB(db *gorm.DB) userMedicationSchedule {
	u.userMedicationScheduleDo.ReplaceDB(db)
	return u
}

type userMedicationScheduleBelongsToUserMedication struct {
	db *gorm.DB

	field.RelationField

	User struct {
		field.RelationField
		FCMTokens struct {
			field.RelationField
			User struct {
				field.RelationField
			}
		}
	}
	Medication struct {
		field.RelationField
	}
	Schedule struct {
		field.RelationField
		UserMedication struct {
			field.RelationField
		}
	}
}

func (a userMedicationScheduleBelongsToUserMedication) Where(conds ...field.Expr) *userMedicationScheduleBelongsToUserMedication {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a userMedicationScheduleBelongsToUserMedication) WithContext(ctx context.Context) *userMedicationScheduleBelongsToUserMedication {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a userMedicationScheduleBelongsToUserMedication) Session(session *gorm.Session) *userMedicationScheduleBelongsToUserMedication {
	a.db = a.db.Session(session)
	return &a
}

func (a userMedicationScheduleBelongsToUserMedication) Model(m *models.UserMedicationSchedule) *userMedicationScheduleBelongsToUserMedicationTx {
	return &userMedicationScheduleBelongsToUserMedicationTx{a.db.Model(m).Association(a.Name())}
}

type userMedicationScheduleBelongsToUserMedicationTx struct{ tx *gorm.Association }

func (a userMedicationScheduleBelongsToUserMedicationTx) Find() (result *models.UserMedication, err error) {
	return result, a.tx.Find(&result)
}

func (a userMedicationScheduleBelongsToUserMedicationTx) Append(values ...*models.UserMedication) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a userMedicationScheduleBelongsToUserMedicationTx) Replace(values ...*models.UserMedication) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a userMedicationScheduleBelongsToUserMedicationTx) Delete(values ...*models.UserMedication) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a userMedicationScheduleBelongsToUserMedicationTx) Clear() error {
	return a.tx.Clear()
}

func (a userMedicationScheduleBelongsToUserMedicationTx) Count() int64 {
	return a.tx.Count()
}

type userMedicationScheduleDo struct{ gen.DO }

type IUserMedicationScheduleDo interface {
	gen.SubQuery
	Debug() IUserMedicationScheduleDo
	WithContext(ctx context.Context) IUserMedicationScheduleDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IUserMedicationScheduleDo
	WriteDB() IUserMedicationScheduleDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IUserMedicationScheduleDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IUserMedicationScheduleDo
	Not(conds ...gen.Condition) IUserMedicationScheduleDo
	Or(conds ...gen.Condition) IUserMedicationScheduleDo
	Select(conds ...field.Expr) IUserMedicationScheduleDo
	Where(conds ...gen.Condition) IUserMedicationScheduleDo
	Order(conds ...field.Expr) IUserMedicationScheduleDo
	Distinct(cols ...field.Expr) IUserMedicationScheduleDo
	Omit(cols ...field.Expr) IUserMedicationScheduleDo
	Join(table schema.Tabler, on ...field.Expr) IUserMedicationScheduleDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IUserMedicationScheduleDo
	RightJoin(table schema.Tabler, on ...field.Expr) IUserMedicationScheduleDo
	Group(cols ...field.Expr) IUserMedicationScheduleDo
	Having(conds ...gen.Condition) IUserMedicationScheduleDo
	Limit(limit int) IUserMedicationScheduleDo
	Offset(offset int) IUserMedicationScheduleDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IUserMedicationScheduleDo
	Unscoped() IUserMedicationScheduleDo
	Create(values ...*models.UserMedicationSchedule) error
	CreateInBatches(values []*models.UserMedicationSchedule, batchSize int) error
	Save(values ...*models.UserMedicationSchedule) error
	First() (*models.UserMedicationSchedule, error)
	Take() (*models.UserMedicationSchedule, error)
	Last() (*models.UserMedicationSchedule, error)
	Find() ([]*models.UserMedicationSchedule, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.UserMedicationSchedule, err error)
	FindInBatches(result *[]*models.UserMedicationSchedule, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.UserMedicationSchedule) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IUserMedicationScheduleDo
	Assign(attrs ...field.AssignExpr) IUserMedicationScheduleDo
	Joins(fields ...field.RelationField) IUserMedicationScheduleDo
	Preload(fields ...field.RelationField) IUserMedicationScheduleDo
	FirstOrInit() (*models.UserMedicationSchedule, error)
	FirstOrCreate() (*models.UserMedicationSchedule, error)
	FindByPage(offset int, limit int) (result []*models.UserMedicationSchedule, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IUserMedicationScheduleDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (u userMedicationScheduleDo) Debug() IUserMedicationScheduleDo {
	return u.withDO(u.DO.Debug())
}

func (u userMedicationScheduleDo) WithContext(ctx context.Context) IUserMedicationScheduleDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u userMedicationScheduleDo) ReadDB() IUserMedicationScheduleDo {
	return u.Clauses(dbresolver.Read)
}

func (u userMedicationScheduleDo) WriteDB() IUserMedicationScheduleDo {
	return u.Clauses(dbresolver.Write)
}

func (u userMedicationScheduleDo) Session(config *gorm.Session) IUserMedicationScheduleDo {
	return u.withDO(u.DO.Session(config))
}

func (u userMedicationScheduleDo) Clauses(conds ...clause.Expression) IUserMedicationScheduleDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u userMedicationScheduleDo) Returning(value interface{}, columns ...string) IUserMedicationScheduleDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u userMedicationScheduleDo) Not(conds ...gen.Condition) IUserMedicationScheduleDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u userMedicationScheduleDo) Or(conds ...gen.Condition) IUserMedicationScheduleDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u userMedicationScheduleDo) Select(conds ...field.Expr) IUserMedicationScheduleDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u userMedicationScheduleDo) Where(conds ...gen.Condition) IUserMedicationScheduleDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u userMedicationScheduleDo) Order(conds ...field.Expr) IUserMedicationScheduleDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u userMedicationScheduleDo) Distinct(cols ...field.Expr) IUserMedicationScheduleDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u userMedicationScheduleDo) Omit(cols ...field.Expr) IUserMedicationScheduleDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u userMedicationScheduleDo) Join(table schema.Tabler, on ...field.Expr) IUserMedicationScheduleDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u userMedicationScheduleDo) LeftJoin(table schema.Tabler, on ...field.Expr) IUserMedicationScheduleDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u userMedicationScheduleDo) RightJoin(table schema.Tabler, on ...field.Expr) IUserMedicationScheduleDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u userMedicationScheduleDo) Group(cols ...field.Expr) IUserMedicationScheduleDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u userMedicationScheduleDo) Having(conds ...gen.Condition) IUserMedicationScheduleDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u userMedicationScheduleDo) Limit(limit int) IUserMedicationScheduleDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u userMedicationScheduleDo) Offset(offset int) IUserMedicationScheduleDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u userMedicationScheduleDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IUserMedicationScheduleDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u userMedicationScheduleDo) Unscoped() IUserMedicationScheduleDo {
	return u.withDO(u.DO.Unscoped())
}

func (u userMedicationScheduleDo) Create(values ...*models.UserMedicationSchedule) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u userMedicationScheduleDo) CreateInBatches(values []*models.UserMedicationSchedule, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u userMedicationScheduleDo) Save(values ...*models.UserMedicationSchedule) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u userMedicationScheduleDo) First() (*models.UserMedicationSchedule, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.UserMedicationSchedule), nil
	}
}

func (u userMedicationScheduleDo) Take() (*models.UserMedicationSchedule, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.UserMedicationSchedule), nil
	}
}

func (u userMedicationScheduleDo) Last() (*models.UserMedicationSchedule, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.UserMedicationSchedule), nil
	}
}

func (u userMedicationScheduleDo) Find() ([]*models.UserMedicationSchedule, error) {
	result, err := u.DO.Find()
	return result.([]*models.UserMedicationSchedule), err
}

func (u userMedicationScheduleDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.UserMedicationSchedule, err error) {
	buf := make([]*models.UserMedicationSchedule, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u userMedicationScheduleDo) FindInBatches(result *[]*models.UserMedicationSchedule, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u userMedicationScheduleDo) Attrs(attrs ...field.AssignExpr) IUserMedicationScheduleDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u userMedicationScheduleDo) Assign(attrs ...field.AssignExpr) IUserMedicationScheduleDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u userMedicationScheduleDo) Joins(fields ...field.RelationField) IUserMedicationScheduleDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u userMedicationScheduleDo) Preload(fields ...field.RelationField) IUserMedicationScheduleDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u userMedicationScheduleDo) FirstOrInit() (*models.UserMedicationSchedule, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.UserMedicationSchedule), nil
	}
}

func (u userMedicationScheduleDo) FirstOrCreate() (*models.UserMedicationSchedule, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.UserMedicationSchedule), nil
	}
}

func (u userMedicationScheduleDo) FindByPage(offset int, limit int) (result []*models.UserMedicationSchedule, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u userMedicationScheduleDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u userMedicationScheduleDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u userMedicationScheduleDo) Delete(models ...*models.UserMedicationSchedule) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *userMedicationScheduleDo) withDO(do gen.Dao) *userMedicationScheduleDo {
	u.DO = *do.(*gen.DO)
	return u
}
