// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/joshnissenbaum/scriptag-platform/shared/models"
)

func newUserFCMToken(db *gorm.DB, opts ...gen.DOOption) userFCMToken {
	_userFCMToken := userFCMToken{}

	_userFCMToken.userFCMTokenDo.UseDB(db, opts...)
	_userFCMToken.userFCMTokenDo.UseModel(&models.UserFCMToken{})

	tableName := _userFCMToken.userFCMTokenDo.TableName()
	_userFCMToken.ALL = field.NewAsterisk(tableName)
	_userFCMToken.ID = field.NewString(tableName, "id")
	_userFCMToken.CreatedAt = field.NewTime(tableName, "created_at")
	_userFCMToken.UpdatedAt = field.NewTime(tableName, "updated_at")
	_userFCMToken.DeletedAt = field.NewField(tableName, "deleted_at")
	_userFCMToken.Token = field.NewString(tableName, "token")
	_userFCMToken.UserID = field.NewString(tableName, "user_id")
	_userFCMToken.User = userFCMTokenBelongsToUser{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("User", "models.User"),
		FCMTokens: struct {
			field.RelationField
			User struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("User.FCMTokens", "models.UserFCMToken"),
			User: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("User.FCMTokens.User", "models.User"),
			},
		},
	}

	_userFCMToken.fillFieldMap()

	return _userFCMToken
}

type userFCMToken struct {
	userFCMTokenDo

	ALL       field.Asterisk
	ID        field.String
	CreatedAt field.Time
	UpdatedAt field.Time
	DeletedAt field.Field
	Token     field.String
	UserID    field.String
	User      userFCMTokenBelongsToUser

	fieldMap map[string]field.Expr
}

func (u userFCMToken) Table(newTableName string) *userFCMToken {
	u.userFCMTokenDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u userFCMToken) As(alias string) *userFCMToken {
	u.userFCMTokenDo.DO = *(u.userFCMTokenDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *userFCMToken) updateTableName(table string) *userFCMToken {
	u.ALL = field.NewAsterisk(table)
	u.ID = field.NewString(table, "id")
	u.CreatedAt = field.NewTime(table, "created_at")
	u.UpdatedAt = field.NewTime(table, "updated_at")
	u.DeletedAt = field.NewField(table, "deleted_at")
	u.Token = field.NewString(table, "token")
	u.UserID = field.NewString(table, "user_id")

	u.fillFieldMap()

	return u
}

func (u *userFCMToken) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *userFCMToken) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 7)
	u.fieldMap["id"] = u.ID
	u.fieldMap["created_at"] = u.CreatedAt
	u.fieldMap["updated_at"] = u.UpdatedAt
	u.fieldMap["deleted_at"] = u.DeletedAt
	u.fieldMap["token"] = u.Token
	u.fieldMap["user_id"] = u.UserID

}

func (u userFCMToken) clone(db *gorm.DB) userFCMToken {
	u.userFCMTokenDo.ReplaceConnPool(db.Statement.ConnPool)
	return u
}

func (u userFCMToken) replaceDB(db *gorm.DB) userFCMToken {
	u.userFCMTokenDo.ReplaceDB(db)
	return u
}

type userFCMTokenBelongsToUser struct {
	db *gorm.DB

	field.RelationField

	FCMTokens struct {
		field.RelationField
		User struct {
			field.RelationField
		}
	}
}

func (a userFCMTokenBelongsToUser) Where(conds ...field.Expr) *userFCMTokenBelongsToUser {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a userFCMTokenBelongsToUser) WithContext(ctx context.Context) *userFCMTokenBelongsToUser {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a userFCMTokenBelongsToUser) Session(session *gorm.Session) *userFCMTokenBelongsToUser {
	a.db = a.db.Session(session)
	return &a
}

func (a userFCMTokenBelongsToUser) Model(m *models.UserFCMToken) *userFCMTokenBelongsToUserTx {
	return &userFCMTokenBelongsToUserTx{a.db.Model(m).Association(a.Name())}
}

type userFCMTokenBelongsToUserTx struct{ tx *gorm.Association }

func (a userFCMTokenBelongsToUserTx) Find() (result *models.User, err error) {
	return result, a.tx.Find(&result)
}

func (a userFCMTokenBelongsToUserTx) Append(values ...*models.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a userFCMTokenBelongsToUserTx) Replace(values ...*models.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a userFCMTokenBelongsToUserTx) Delete(values ...*models.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a userFCMTokenBelongsToUserTx) Clear() error {
	return a.tx.Clear()
}

func (a userFCMTokenBelongsToUserTx) Count() int64 {
	return a.tx.Count()
}

type userFCMTokenDo struct{ gen.DO }

type IUserFCMTokenDo interface {
	gen.SubQuery
	Debug() IUserFCMTokenDo
	WithContext(ctx context.Context) IUserFCMTokenDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IUserFCMTokenDo
	WriteDB() IUserFCMTokenDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IUserFCMTokenDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IUserFCMTokenDo
	Not(conds ...gen.Condition) IUserFCMTokenDo
	Or(conds ...gen.Condition) IUserFCMTokenDo
	Select(conds ...field.Expr) IUserFCMTokenDo
	Where(conds ...gen.Condition) IUserFCMTokenDo
	Order(conds ...field.Expr) IUserFCMTokenDo
	Distinct(cols ...field.Expr) IUserFCMTokenDo
	Omit(cols ...field.Expr) IUserFCMTokenDo
	Join(table schema.Tabler, on ...field.Expr) IUserFCMTokenDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IUserFCMTokenDo
	RightJoin(table schema.Tabler, on ...field.Expr) IUserFCMTokenDo
	Group(cols ...field.Expr) IUserFCMTokenDo
	Having(conds ...gen.Condition) IUserFCMTokenDo
	Limit(limit int) IUserFCMTokenDo
	Offset(offset int) IUserFCMTokenDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IUserFCMTokenDo
	Unscoped() IUserFCMTokenDo
	Create(values ...*models.UserFCMToken) error
	CreateInBatches(values []*models.UserFCMToken, batchSize int) error
	Save(values ...*models.UserFCMToken) error
	First() (*models.UserFCMToken, error)
	Take() (*models.UserFCMToken, error)
	Last() (*models.UserFCMToken, error)
	Find() ([]*models.UserFCMToken, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.UserFCMToken, err error)
	FindInBatches(result *[]*models.UserFCMToken, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.UserFCMToken) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IUserFCMTokenDo
	Assign(attrs ...field.AssignExpr) IUserFCMTokenDo
	Joins(fields ...field.RelationField) IUserFCMTokenDo
	Preload(fields ...field.RelationField) IUserFCMTokenDo
	FirstOrInit() (*models.UserFCMToken, error)
	FirstOrCreate() (*models.UserFCMToken, error)
	FindByPage(offset int, limit int) (result []*models.UserFCMToken, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IUserFCMTokenDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (u userFCMTokenDo) Debug() IUserFCMTokenDo {
	return u.withDO(u.DO.Debug())
}

func (u userFCMTokenDo) WithContext(ctx context.Context) IUserFCMTokenDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u userFCMTokenDo) ReadDB() IUserFCMTokenDo {
	return u.Clauses(dbresolver.Read)
}

func (u userFCMTokenDo) WriteDB() IUserFCMTokenDo {
	return u.Clauses(dbresolver.Write)
}

func (u userFCMTokenDo) Session(config *gorm.Session) IUserFCMTokenDo {
	return u.withDO(u.DO.Session(config))
}

func (u userFCMTokenDo) Clauses(conds ...clause.Expression) IUserFCMTokenDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u userFCMTokenDo) Returning(value interface{}, columns ...string) IUserFCMTokenDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u userFCMTokenDo) Not(conds ...gen.Condition) IUserFCMTokenDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u userFCMTokenDo) Or(conds ...gen.Condition) IUserFCMTokenDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u userFCMTokenDo) Select(conds ...field.Expr) IUserFCMTokenDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u userFCMTokenDo) Where(conds ...gen.Condition) IUserFCMTokenDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u userFCMTokenDo) Order(conds ...field.Expr) IUserFCMTokenDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u userFCMTokenDo) Distinct(cols ...field.Expr) IUserFCMTokenDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u userFCMTokenDo) Omit(cols ...field.Expr) IUserFCMTokenDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u userFCMTokenDo) Join(table schema.Tabler, on ...field.Expr) IUserFCMTokenDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u userFCMTokenDo) LeftJoin(table schema.Tabler, on ...field.Expr) IUserFCMTokenDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u userFCMTokenDo) RightJoin(table schema.Tabler, on ...field.Expr) IUserFCMTokenDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u userFCMTokenDo) Group(cols ...field.Expr) IUserFCMTokenDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u userFCMTokenDo) Having(conds ...gen.Condition) IUserFCMTokenDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u userFCMTokenDo) Limit(limit int) IUserFCMTokenDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u userFCMTokenDo) Offset(offset int) IUserFCMTokenDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u userFCMTokenDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IUserFCMTokenDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u userFCMTokenDo) Unscoped() IUserFCMTokenDo {
	return u.withDO(u.DO.Unscoped())
}

func (u userFCMTokenDo) Create(values ...*models.UserFCMToken) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u userFCMTokenDo) CreateInBatches(values []*models.UserFCMToken, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u userFCMTokenDo) Save(values ...*models.UserFCMToken) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u userFCMTokenDo) First() (*models.UserFCMToken, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.UserFCMToken), nil
	}
}

func (u userFCMTokenDo) Take() (*models.UserFCMToken, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.UserFCMToken), nil
	}
}

func (u userFCMTokenDo) Last() (*models.UserFCMToken, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.UserFCMToken), nil
	}
}

func (u userFCMTokenDo) Find() ([]*models.UserFCMToken, error) {
	result, err := u.DO.Find()
	return result.([]*models.UserFCMToken), err
}

func (u userFCMTokenDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.UserFCMToken, err error) {
	buf := make([]*models.UserFCMToken, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u userFCMTokenDo) FindInBatches(result *[]*models.UserFCMToken, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u userFCMTokenDo) Attrs(attrs ...field.AssignExpr) IUserFCMTokenDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u userFCMTokenDo) Assign(attrs ...field.AssignExpr) IUserFCMTokenDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u userFCMTokenDo) Joins(fields ...field.RelationField) IUserFCMTokenDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u userFCMTokenDo) Preload(fields ...field.RelationField) IUserFCMTokenDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u userFCMTokenDo) FirstOrInit() (*models.UserFCMToken, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.UserFCMToken), nil
	}
}

func (u userFCMTokenDo) FirstOrCreate() (*models.UserFCMToken, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.UserFCMToken), nil
	}
}

func (u userFCMTokenDo) FindByPage(offset int, limit int) (result []*models.UserFCMToken, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u userFCMTokenDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u userFCMTokenDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u userFCMTokenDo) Delete(models ...*models.UserFCMToken) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *userFCMTokenDo) withDO(do gen.Dao) *userFCMTokenDo {
	u.DO = *do.(*gen.DO)
	return u
}
