// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/joshnissenbaum/scriptag-platform/shared/models"
)

func newUserMedication(db *gorm.DB, opts ...gen.DOOption) userMedication {
	_userMedication := userMedication{}

	_userMedication.userMedicationDo.UseDB(db, opts...)
	_userMedication.userMedicationDo.UseModel(&models.UserMedication{})

	tableName := _userMedication.userMedicationDo.TableName()
	_userMedication.ALL = field.NewAsterisk(tableName)
	_userMedication.ID = field.NewString(tableName, "id")
	_userMedication.CreatedAt = field.NewTime(tableName, "created_at")
	_userMedication.UpdatedAt = field.NewTime(tableName, "updated_at")
	_userMedication.DeletedAt = field.NewField(tableName, "deleted_at")
	_userMedication.UserID = field.NewString(tableName, "user_id")
	_userMedication.MedicationID = field.NewString(tableName, "medication_id")
	_userMedication.Name = field.NewString(tableName, "name")
	_userMedication.Strength = field.NewString(tableName, "strength")
	_userMedication.TagLinked = field.NewBool(tableName, "tag_linked")
	_userMedication.Schedule = userMedicationHasOneSchedule{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Schedule", "models.UserMedicationSchedule"),
		UserMedication: struct {
			field.RelationField
			User struct {
				field.RelationField
				FCMTokens struct {
					field.RelationField
					User struct {
						field.RelationField
					}
				}
			}
			Medication struct {
				field.RelationField
			}
			Schedule struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Schedule.UserMedication", "models.UserMedication"),
			User: struct {
				field.RelationField
				FCMTokens struct {
					field.RelationField
					User struct {
						field.RelationField
					}
				}
			}{
				RelationField: field.NewRelation("Schedule.UserMedication.User", "models.User"),
				FCMTokens: struct {
					field.RelationField
					User struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Schedule.UserMedication.User.FCMTokens", "models.UserFCMToken"),
					User: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Schedule.UserMedication.User.FCMTokens.User", "models.User"),
					},
				},
			},
			Medication: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Schedule.UserMedication.Medication", "models.Medication"),
			},
			Schedule: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Schedule.UserMedication.Schedule", "models.UserMedicationSchedule"),
			},
		},
	}

	_userMedication.User = userMedicationBelongsToUser{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("User", "models.User"),
	}

	_userMedication.Medication = userMedicationBelongsToMedication{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Medication", "models.Medication"),
	}

	_userMedication.fillFieldMap()

	return _userMedication
}

type userMedication struct {
	userMedicationDo

	ALL          field.Asterisk
	ID           field.String
	CreatedAt    field.Time
	UpdatedAt    field.Time
	DeletedAt    field.Field
	UserID       field.String
	MedicationID field.String
	Name         field.String
	Strength     field.String
	TagLinked    field.Bool
	Schedule     userMedicationHasOneSchedule

	User userMedicationBelongsToUser

	Medication userMedicationBelongsToMedication

	fieldMap map[string]field.Expr
}

func (u userMedication) Table(newTableName string) *userMedication {
	u.userMedicationDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u userMedication) As(alias string) *userMedication {
	u.userMedicationDo.DO = *(u.userMedicationDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *userMedication) updateTableName(table string) *userMedication {
	u.ALL = field.NewAsterisk(table)
	u.ID = field.NewString(table, "id")
	u.CreatedAt = field.NewTime(table, "created_at")
	u.UpdatedAt = field.NewTime(table, "updated_at")
	u.DeletedAt = field.NewField(table, "deleted_at")
	u.UserID = field.NewString(table, "user_id")
	u.MedicationID = field.NewString(table, "medication_id")
	u.Name = field.NewString(table, "name")
	u.Strength = field.NewString(table, "strength")
	u.TagLinked = field.NewBool(table, "tag_linked")

	u.fillFieldMap()

	return u
}

func (u *userMedication) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *userMedication) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 12)
	u.fieldMap["id"] = u.ID
	u.fieldMap["created_at"] = u.CreatedAt
	u.fieldMap["updated_at"] = u.UpdatedAt
	u.fieldMap["deleted_at"] = u.DeletedAt
	u.fieldMap["user_id"] = u.UserID
	u.fieldMap["medication_id"] = u.MedicationID
	u.fieldMap["name"] = u.Name
	u.fieldMap["strength"] = u.Strength
	u.fieldMap["tag_linked"] = u.TagLinked

}

func (u userMedication) clone(db *gorm.DB) userMedication {
	u.userMedicationDo.ReplaceConnPool(db.Statement.ConnPool)
	return u
}

func (u userMedication) replaceDB(db *gorm.DB) userMedication {
	u.userMedicationDo.ReplaceDB(db)
	return u
}

type userMedicationHasOneSchedule struct {
	db *gorm.DB

	field.RelationField

	UserMedication struct {
		field.RelationField
		User struct {
			field.RelationField
			FCMTokens struct {
				field.RelationField
				User struct {
					field.RelationField
				}
			}
		}
		Medication struct {
			field.RelationField
		}
		Schedule struct {
			field.RelationField
		}
	}
}

func (a userMedicationHasOneSchedule) Where(conds ...field.Expr) *userMedicationHasOneSchedule {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a userMedicationHasOneSchedule) WithContext(ctx context.Context) *userMedicationHasOneSchedule {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a userMedicationHasOneSchedule) Session(session *gorm.Session) *userMedicationHasOneSchedule {
	a.db = a.db.Session(session)
	return &a
}

func (a userMedicationHasOneSchedule) Model(m *models.UserMedication) *userMedicationHasOneScheduleTx {
	return &userMedicationHasOneScheduleTx{a.db.Model(m).Association(a.Name())}
}

type userMedicationHasOneScheduleTx struct{ tx *gorm.Association }

func (a userMedicationHasOneScheduleTx) Find() (result *models.UserMedicationSchedule, err error) {
	return result, a.tx.Find(&result)
}

func (a userMedicationHasOneScheduleTx) Append(values ...*models.UserMedicationSchedule) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a userMedicationHasOneScheduleTx) Replace(values ...*models.UserMedicationSchedule) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a userMedicationHasOneScheduleTx) Delete(values ...*models.UserMedicationSchedule) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a userMedicationHasOneScheduleTx) Clear() error {
	return a.tx.Clear()
}

func (a userMedicationHasOneScheduleTx) Count() int64 {
	return a.tx.Count()
}

type userMedicationBelongsToUser struct {
	db *gorm.DB

	field.RelationField
}

func (a userMedicationBelongsToUser) Where(conds ...field.Expr) *userMedicationBelongsToUser {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a userMedicationBelongsToUser) WithContext(ctx context.Context) *userMedicationBelongsToUser {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a userMedicationBelongsToUser) Session(session *gorm.Session) *userMedicationBelongsToUser {
	a.db = a.db.Session(session)
	return &a
}

func (a userMedicationBelongsToUser) Model(m *models.UserMedication) *userMedicationBelongsToUserTx {
	return &userMedicationBelongsToUserTx{a.db.Model(m).Association(a.Name())}
}

type userMedicationBelongsToUserTx struct{ tx *gorm.Association }

func (a userMedicationBelongsToUserTx) Find() (result *models.User, err error) {
	return result, a.tx.Find(&result)
}

func (a userMedicationBelongsToUserTx) Append(values ...*models.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a userMedicationBelongsToUserTx) Replace(values ...*models.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a userMedicationBelongsToUserTx) Delete(values ...*models.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a userMedicationBelongsToUserTx) Clear() error {
	return a.tx.Clear()
}

func (a userMedicationBelongsToUserTx) Count() int64 {
	return a.tx.Count()
}

type userMedicationBelongsToMedication struct {
	db *gorm.DB

	field.RelationField
}

func (a userMedicationBelongsToMedication) Where(conds ...field.Expr) *userMedicationBelongsToMedication {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a userMedicationBelongsToMedication) WithContext(ctx context.Context) *userMedicationBelongsToMedication {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a userMedicationBelongsToMedication) Session(session *gorm.Session) *userMedicationBelongsToMedication {
	a.db = a.db.Session(session)
	return &a
}

func (a userMedicationBelongsToMedication) Model(m *models.UserMedication) *userMedicationBelongsToMedicationTx {
	return &userMedicationBelongsToMedicationTx{a.db.Model(m).Association(a.Name())}
}

type userMedicationBelongsToMedicationTx struct{ tx *gorm.Association }

func (a userMedicationBelongsToMedicationTx) Find() (result *models.Medication, err error) {
	return result, a.tx.Find(&result)
}

func (a userMedicationBelongsToMedicationTx) Append(values ...*models.Medication) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a userMedicationBelongsToMedicationTx) Replace(values ...*models.Medication) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a userMedicationBelongsToMedicationTx) Delete(values ...*models.Medication) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a userMedicationBelongsToMedicationTx) Clear() error {
	return a.tx.Clear()
}

func (a userMedicationBelongsToMedicationTx) Count() int64 {
	return a.tx.Count()
}

type userMedicationDo struct{ gen.DO }

type IUserMedicationDo interface {
	gen.SubQuery
	Debug() IUserMedicationDo
	WithContext(ctx context.Context) IUserMedicationDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IUserMedicationDo
	WriteDB() IUserMedicationDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IUserMedicationDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IUserMedicationDo
	Not(conds ...gen.Condition) IUserMedicationDo
	Or(conds ...gen.Condition) IUserMedicationDo
	Select(conds ...field.Expr) IUserMedicationDo
	Where(conds ...gen.Condition) IUserMedicationDo
	Order(conds ...field.Expr) IUserMedicationDo
	Distinct(cols ...field.Expr) IUserMedicationDo
	Omit(cols ...field.Expr) IUserMedicationDo
	Join(table schema.Tabler, on ...field.Expr) IUserMedicationDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IUserMedicationDo
	RightJoin(table schema.Tabler, on ...field.Expr) IUserMedicationDo
	Group(cols ...field.Expr) IUserMedicationDo
	Having(conds ...gen.Condition) IUserMedicationDo
	Limit(limit int) IUserMedicationDo
	Offset(offset int) IUserMedicationDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IUserMedicationDo
	Unscoped() IUserMedicationDo
	Create(values ...*models.UserMedication) error
	CreateInBatches(values []*models.UserMedication, batchSize int) error
	Save(values ...*models.UserMedication) error
	First() (*models.UserMedication, error)
	Take() (*models.UserMedication, error)
	Last() (*models.UserMedication, error)
	Find() ([]*models.UserMedication, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.UserMedication, err error)
	FindInBatches(result *[]*models.UserMedication, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.UserMedication) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IUserMedicationDo
	Assign(attrs ...field.AssignExpr) IUserMedicationDo
	Joins(fields ...field.RelationField) IUserMedicationDo
	Preload(fields ...field.RelationField) IUserMedicationDo
	FirstOrInit() (*models.UserMedication, error)
	FirstOrCreate() (*models.UserMedication, error)
	FindByPage(offset int, limit int) (result []*models.UserMedication, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IUserMedicationDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (u userMedicationDo) Debug() IUserMedicationDo {
	return u.withDO(u.DO.Debug())
}

func (u userMedicationDo) WithContext(ctx context.Context) IUserMedicationDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u userMedicationDo) ReadDB() IUserMedicationDo {
	return u.Clauses(dbresolver.Read)
}

func (u userMedicationDo) WriteDB() IUserMedicationDo {
	return u.Clauses(dbresolver.Write)
}

func (u userMedicationDo) Session(config *gorm.Session) IUserMedicationDo {
	return u.withDO(u.DO.Session(config))
}

func (u userMedicationDo) Clauses(conds ...clause.Expression) IUserMedicationDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u userMedicationDo) Returning(value interface{}, columns ...string) IUserMedicationDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u userMedicationDo) Not(conds ...gen.Condition) IUserMedicationDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u userMedicationDo) Or(conds ...gen.Condition) IUserMedicationDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u userMedicationDo) Select(conds ...field.Expr) IUserMedicationDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u userMedicationDo) Where(conds ...gen.Condition) IUserMedicationDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u userMedicationDo) Order(conds ...field.Expr) IUserMedicationDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u userMedicationDo) Distinct(cols ...field.Expr) IUserMedicationDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u userMedicationDo) Omit(cols ...field.Expr) IUserMedicationDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u userMedicationDo) Join(table schema.Tabler, on ...field.Expr) IUserMedicationDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u userMedicationDo) LeftJoin(table schema.Tabler, on ...field.Expr) IUserMedicationDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u userMedicationDo) RightJoin(table schema.Tabler, on ...field.Expr) IUserMedicationDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u userMedicationDo) Group(cols ...field.Expr) IUserMedicationDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u userMedicationDo) Having(conds ...gen.Condition) IUserMedicationDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u userMedicationDo) Limit(limit int) IUserMedicationDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u userMedicationDo) Offset(offset int) IUserMedicationDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u userMedicationDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IUserMedicationDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u userMedicationDo) Unscoped() IUserMedicationDo {
	return u.withDO(u.DO.Unscoped())
}

func (u userMedicationDo) Create(values ...*models.UserMedication) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u userMedicationDo) CreateInBatches(values []*models.UserMedication, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u userMedicationDo) Save(values ...*models.UserMedication) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u userMedicationDo) First() (*models.UserMedication, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.UserMedication), nil
	}
}

func (u userMedicationDo) Take() (*models.UserMedication, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.UserMedication), nil
	}
}

func (u userMedicationDo) Last() (*models.UserMedication, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.UserMedication), nil
	}
}

func (u userMedicationDo) Find() ([]*models.UserMedication, error) {
	result, err := u.DO.Find()
	return result.([]*models.UserMedication), err
}

func (u userMedicationDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.UserMedication, err error) {
	buf := make([]*models.UserMedication, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u userMedicationDo) FindInBatches(result *[]*models.UserMedication, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u userMedicationDo) Attrs(attrs ...field.AssignExpr) IUserMedicationDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u userMedicationDo) Assign(attrs ...field.AssignExpr) IUserMedicationDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u userMedicationDo) Joins(fields ...field.RelationField) IUserMedicationDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u userMedicationDo) Preload(fields ...field.RelationField) IUserMedicationDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u userMedicationDo) FirstOrInit() (*models.UserMedication, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.UserMedication), nil
	}
}

func (u userMedicationDo) FirstOrCreate() (*models.UserMedication, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.UserMedication), nil
	}
}

func (u userMedicationDo) FindByPage(offset int, limit int) (result []*models.UserMedication, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u userMedicationDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u userMedicationDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u userMedicationDo) Delete(models ...*models.UserMedication) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *userMedicationDo) withDO(do gen.Dao) *userMedicationDo {
	u.DO = *do.(*gen.DO)
	return u
}
