//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var UserMedicationRecurringScheduleType = &struct {
	Time       postgres.StringExpression
	Intervals  postgres.StringExpression
	Periods    postgres.StringExpression
	WhenNeeded postgres.StringExpression
}{
	Time:       postgres.NewEnumValue("TIME"),
	Intervals:  postgres.NewEnumValue("INTERVALS"),
	Periods:    postgres.NewEnumValue("PERIODS"),
	WhenNeeded: postgres.NewEnumValue("WHEN_NEEDED"),
}
