//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var UserMedicationScheduleLogStatus = &struct {
	Upcoming postgres.StringExpression
	Taken    postgres.StringExpression
	Missed   postgres.StringExpression
}{
	Upcoming: postgres.NewEnumValue("UPCOMING"),
	Taken:    postgres.NewEnumValue("TAKEN"),
	Missed:   postgres.NewEnumValue("MISSED"),
}
