package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.62

import (
	"context"
	"go-api/adapters/loaders"
	adapters "go-api/adapters/models"
	"go-api/auth"
	"go-api/core"
	"go-api/graph/model"
	"time"
)

// AddMyMedication is the resolver for the addMyMedication field.
func (r *mutationResolver) AddMyMedication(ctx context.Context, input model.AddMyMedicationInput) (*model.MyMedication, error) {
	user := auth.ForContext(ctx)

	return r.UserMedicationService.CreateUserMedication(&core.UserMedication{
		MedicationID: input.MedicationID,
		UserID:       user.ID,
		Strength:     *input.DosageStrength,
		BrandName:    *input.Name,
	})
}

// CreateAccount is the resolver for the createAccount field.
func (r *mutationResolver) CreateAccount(ctx context.Context, input model.CreateAccountInput) (*model.Session, error) {
	return r.UserService.CreateUser(ctx, &core.User{
		Email:    input.Email,
		Password: input.Password,
	})
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.Session, error) {
	return r.UserService.LoginUser(ctx, input.Email, input.Password)
}

// AddFcmToken is the resolver for the addFcmToken field.
func (r *mutationResolver) AddFcmToken(ctx context.Context, token string) (bool, error) {
	user := auth.ForContext(ctx)
	err := r.UserService.AddFCMToken(ctx, user, token)

	if err != nil {
		return false, err
	} else {
		return true, nil
	}
}

// CreateMedicationSchedule is the resolver for the createMedicationSchedule field.
func (r *mutationResolver) CreateMedicationSchedule(ctx context.Context, input model.AddMedicationScheduleInput) (bool, error) {
	user := auth.ForContext(ctx)

	return r.UserMedicationService.CreateUserMedicationSchedule(&core.MedicationSchedule{
		MedicationID:     input.MedicationID,
		UserMedicationID: input.MyMedicationID,
		MethodType:       adapters.MethodType(*input.MethodType),
		RecurringType:    adapters.RecurringType(*input.RecurringType),
		DaysOfWeek:       input.DaysOfWeek,
		TimeSlots:        input.TimeSlots,
		StartDate:        input.StartDate,
		EndDate:          input.EndDate,
		DaysInterval:     input.IntervalsDays,
		HoursInterval:    input.IntervalsHours,
		UseForDays:       input.UseForDays,
		PauseForDays:     input.PauseForDays,
		UseForHours:      input.UseForHours,
		PauseForHours:    input.PauseForHours,
		RefillsAmount:    input.RefillsRemaining,
		DosesAmount:      input.DosesRemaining,
	}, user.ID, r.GormDB)
}

// UpdateMedicationTagLinked is the resolver for the updateMedicationTagLinked field.
func (r *mutationResolver) UpdateMedicationTagLinked(ctx context.Context, input model.UpdateMedicationTagLinkedInput) (bool, error) {
	user := auth.ForContext(ctx)

	return r.UserMedicationService.UpdateUserMedicationTagLinked(user.ID, input.MyMedicationID, input.IsTagLinked)
}

// TagScanned is the resolver for the tagScanned field.
func (r *mutationResolver) TagScanned(ctx context.Context, input model.TagScannedInput) (bool, error) {
	user := auth.ForContext(ctx)

	return r.UserMedicationService.OnTagScanned(user.ID, input.MedicationID)
}

// Schedule is the resolver for the schedule field.
func (r *myMedicationResolver) Schedule(ctx context.Context, obj *model.MyMedication) (*model.MyMedicationSchedule, error) {
	return loaders.GetMedicationSchedule(ctx, obj.ID)
}

// SearchMedications is the resolver for the searchMedications field.
func (r *queryResolver) SearchMedications(ctx context.Context, query string, after *string) (*model.MedicationsConnection, error) {
	return r.MedicationService.SearchMedications(query, after)
}

// MyMedications is the resolver for the myMedications field.
func (r *queryResolver) MyMedications(ctx context.Context, after *string) (*model.MyMedicationsConnection, error) {
	user := auth.ForContext(ctx)

	return r.UserMedicationService.FetchUserMedications(user.ID, after)
}

// MedicationLogEntries is the resolver for the medicationLogEntries field.
func (r *queryResolver) MedicationLogEntries(ctx context.Context, date time.Time) ([]*model.MedicationLogEntry, error) {
	user := auth.ForContext(ctx)

	return r.UserMedicationService.FetchLogHistory(user.ID, date)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// MyMedication returns MyMedicationResolver implementation.
func (r *Resolver) MyMedication() MyMedicationResolver { return &myMedicationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type myMedicationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
