package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.56

import (
	"context"
	"fmt"
	"go-api/auth"
	"go-api/core"
	"go-api/graph/model"
)

// AddMyMedication is the resolver for the addMyMedication field.
func (r *mutationResolver) AddMyMedication(ctx context.Context, input model.AddMyMedicationInput) (*model.MyMedication, error) {
	user := auth.ForContext(ctx)

	return r.UserMedicationService.CreateUserMedication(&core.UserMedication{
		MedicationID: input.MedicationID,
		UserID:       user.ID,
		Strength:     *input.DosageStrength,
		BrandName:    *input.Name,
	})
}

// CreateAccount is the resolver for the createAccount field.
func (r *mutationResolver) CreateAccount(ctx context.Context, input model.CreateAccountInput) (*model.Session, error) {
	return r.UserService.CreateUser(ctx, &core.User{
		Email:    input.Email,
		Password: input.Password,
	})
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.Session, error) {
	return r.UserService.LoginUser(ctx, input.Email, input.Password)
}

// AddFcmToken is the resolver for the addFcmToken field.
func (r *mutationResolver) AddFcmToken(ctx context.Context, token string) (bool, error) {
	user := auth.ForContext(ctx)
	err := r.UserService.AddFCMToken(ctx, user, token)

	if err != nil {
		return false, err
	} else {
		return true, nil
	}
}

// CreateMedicationSchedule is the resolver for the createMedicationSchedule field.
func (r *mutationResolver) CreateMedicationSchedule(ctx context.Context, input model.AddMedicationScheduleInput) (bool, error) {
	// user := auth.ForContext(ctx)

	return r.UserMedicationService.CreateUserMedicationSchedule(&core.MedicationSchedule{
		UserMedicationID: *input.MyMedicationID,
		MethodType:       *input.MethodType,
		RecurringType:    *input.RecurringType,
		DaysOfWeek:       input.DaysOfWeek,
		TimeSlots:        input.TimeSlots,
		StartDate:        input.StartDate,
		EndDate:          input.EndDate,
		DaysInterval:     input.IntervalsDays,
		HoursInterval:    input.IntervalsHours,
		UseForDays:       input.UseForDays,
		PauseForDays:     input.PauseForDays,
		UseForHours:      input.UseForHours,
		PauseForHours:    input.PauseForHours,
		RefillsAmount:    input.RefillsRemaining,
		DosesAmount:      input.DosesRemaining,
	})
}

// SearchMedications is the resolver for the searchMedications field.
func (r *queryResolver) SearchMedications(ctx context.Context, query string, after *string) (*model.MedicationsConnection, error) {
	return r.MedicationService.SearchMedications(query, after)
}

// MyMedications is the resolver for the myMedications field.
func (r *queryResolver) MyMedications(ctx context.Context) ([]*model.MyMedicationEdge, error) {
	panic(fmt.Errorf("not implemented: MyMedications - myMedications"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
