package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.56

import (
	"context"
	"fmt"
	"go-api/auth"
	"go-api/core"
	"go-api/graph/model"
)

// AddMyMedication is the resolver for the addMyMedication field.
func (r *mutationResolver) AddMyMedication(ctx context.Context, input model.AddMyMedicationInput) (*model.MyMedication, error) {
	user := auth.ForContext(ctx)

	return r.MedicationService.CreateUserMedication(&core.UserMedication{
		MedicationID:     input.MedicationID,
		UserID:           user.ID,
		Strength:         input.DosageStrength,
		ReminderDateTime: input.ConsumptionTime,
	})
}

// CreateAccount is the resolver for the createAccount field.
func (r *mutationResolver) CreateAccount(ctx context.Context, input model.CreateAccountInput) (*model.Session, error) {
	return r.UserService.CreateUser(ctx, &core.User{
		Email:    input.Email,
		Password: input.Password,
	})
}

// AddFcmToken is the resolver for the addFcmToken field.
func (r *mutationResolver) AddFcmToken(ctx context.Context, token string) (bool, error) {
	user := auth.ForContext(ctx)
	err := r.UserService.AddFCMToken(ctx, user, token)

	if err != nil {
		return false, err
	} else {
		return true, nil
	}
}

// SearchMedications is the resolver for the searchMedications field.
func (r *queryResolver) SearchMedications(ctx context.Context, query string) (*model.MedicationsConnection, error) {
	return r.MedicationService.SearchMedications(query)
}

// MyMedications is the resolver for the myMedications field.
func (r *queryResolver) MyMedications(ctx context.Context) ([]*model.MyMedicationEdge, error) {
	panic(fmt.Errorf("not implemented: MyMedications - myMedications"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
